export const cribs = [
  {
    id: "1",
    caption: "A cozy Crib",
    BR: 2,
    BTH: 2,
    form: "Condo",
    pet: "No",
    maxGuestsAllowed: 5,
    price: 200,
    securityDeposit: 150,
    maxNoOfNights: 5,
    ownersDetails: {
      name: "John Doe",
      phoneNo: +2348012345678,
      verified: "Yes",
    },
    long: 1.001234,
    lat: 17.2345,
    images: ["./city.jpg", "./mountain.jpg", "./road.jpg"],

    address: {
      street: "1367 legit Blvd.",
      city: "Dapids City",
      zipcode: 10123,
    },
    wheelchairAccessibility: "Yes",
    entrance: "Access Code",
    Description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident iure totam corrupti eveniet officia maxime eaque laudantium alias quisquam praesentium voluptatum aliquid, reprehenderit veniam ducimus magni a necessitatibus cumque ipsum pariatur odit blanditiis porro velit perspiciatis asperiores? Sunt explicabo tempora harum fugit sequi eveniet minima itaque dolores aut vitae molestiae tempore maiores, fugiat aspernatur. Tenetur hic itaque obcaecati! Vitae saepe animi quidem similique tempore? Ipsam, voluptatibus. Libero perferendis illum atque ipsam neque tenetur quasi iste perspiciatis repellendus quae eum porro numquam, vitae odio, velit animi cupiditate consequuntur unde dolore laborum suscipit ad sunt. Amet dolore maxime asperiores deleniti dolores! Aspernatur?",
  },
  {
    id: "2",
    caption: "A Beautiful Townhouse",
    BR: 4,
    BTH: 5,
    form: "Townhouse",
    pet: "No",
    maxGuestsAllowed: 12,
    price: 350,
    securityDeposit: 180,
    maxNoOfNights: 7,
    ownersDetails: {
      name: "Adam Appleseed",
      phoneNo: +2348012387654,
      verified: "Yes",
    },
    long: 11.001234,
    lat: 60.769345,
    images: ["./city.jpg", "./mountain.jpg", "./road.jpg"],

    address: {
      street: "67 Curve Drive.",
      city: "Sipple County",
      zipcode: 90423,
    },

    wheelchairAccessibility: "No",
    entrance: "Key",
    Description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident iure totam corrupti eveniet officia maxime eaque laudantium alias quisquam praesentium voluptatum aliquid, reprehenderit veniam ducimus magni a necessitatibus cumque ipsum pariatur odit blanditiis porro velit perspiciatis asperiores? Sunt explicabo tempora harum fugit sequi eveniet minima itaque dolores aut vitae molestiae tempore maiores, fugiat aspernatur. Tenetur hic itaque obcaecati! Vitae saepe animi quidem similique tempore? Ipsam, voluptatibus. Libero perferendis illum atque ipsam neque tenetur quasi iste perspiciatis repellendus quae eum porro numquam, vitae odio, velit animi cupiditate consequuntur unde dolore laborum suscipit ad sunt. Amet dolore maxime asperiores deleniti dolores! Aspernatur?",
  },
  {
    id: "3",
    caption: "Spacious House for Events",
    BR: 6,
    BTH: 5,
    form: "House",
    pet: "Yes",
    maxGuestsAllowed: 15,
    price: 500,
    securityDeposit: 450,
    maxNoOfNights: 6,
    ownersDetails: {
      name: "Eve Dangletan",
      phoneNo: +2348062848730,
      verified: "Yes",
    },
    long: 32.001234,
    lat: 101.2345,
    images: ["./city.jpg", "./mountain.jpg", "./road.jpg"],

    address: {
      street: "39 Straight Lane.",
      city: "Mountain City",
      zipcode: 71523,
    },
    wheelchairAccessibility: "Yes",
    entrance: "Access Code",
    Description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident iure totam corrupti eveniet officia maxime eaque laudantium alias quisquam praesentium voluptatum aliquid, reprehenderit veniam ducimus magni a necessitatibus cumque ipsum pariatur odit blanditiis porro velit perspiciatis asperiores? Sunt explicabo tempora harum fugit sequi eveniet minima itaque dolores aut vitae molestiae tempore maiores, fugiat aspernatur. Tenetur hic itaque obcaecati! Vitae saepe animi quidem similique tempore? Ipsam, voluptatibus. Libero perferendis illum atque ipsam neque tenetur quasi iste perspiciatis repellendus quae eum porro numquam, vitae odio, velit animi cupiditate consequuntur unde dolore laborum suscipit ad sunt. Amet dolore maxime asperiores deleniti dolores! Aspernatur?",
  },
  {
    id: "4",
    caption: "Studio in Central Location",
    BR: 1,
    BTH: 1,
    form: "Studio",
    pet: "No",
    maxGuestsAllowed: 2,
    price: 99,
    securityDeposit: 100,
    maxNoOfNights: 14,
    ownersDetails: {
      name: "Fred Ducant",
      phoneNo: +2347028937442,
      verified: "No",
    },
    long: 51.001234,
    lat: 303.2345,
    images: ["./city.jpg", "./mountain.jpg", "./road.jpg"],

    address: {
      street: "89 Lamb Drive Estate.",
      city: "Old Luke City",
      zipcode: 89320,
    },
    wheelchairAccessibility: "No",
    entrance: "Access Code",
    Description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident iure totam corrupti eveniet officia maxime eaque laudantium alias quisquam praesentium voluptatum aliquid, reprehenderit veniam ducimus magni a necessitatibus cumque ipsum pariatur odit blanditiis porro velit perspiciatis asperiores? Sunt explicabo tempora harum fugit sequi eveniet minima itaque dolores aut vitae molestiae tempore maiores, fugiat aspernatur. Tenetur hic itaque obcaecati! Vitae saepe animi quidem similique tempore? Ipsam, voluptatibus. Libero perferendis illum atque ipsam neque tenetur quasi iste perspiciatis repellendus quae eum porro numquam, vitae odio, velit animi cupiditate consequuntur unde dolore laborum suscipit ad sunt. Amet dolore maxime asperiores deleniti dolores! Aspernatur?",
  },
  {
    id: "5",
    caption: "Uptown Penthouse Condo",
    BR: 2,
    BTH: 1,
    form: "Condo",
    pet: "No",
    maxGuestsAllowed: 4,
    price: 550,
    securityDeposit: 370,
    maxNoOfNights: 5,
    ownersDetails: {
      name: "Ingrid Barouche",
      phoneNo: +2348098678543,
      verified: "No",
    },
    long: 90.001234,
    lat: 84.2345,
    images: ["./city.jpg", "./mountain.jpg", "./road.jpg"],

    address: {
      street: "99 101th street.",
      city: "Sithako",
      zipcode: 52941,
    },
    wheelchairAccessibility: "Yes",
    entrance: "Key",
    Description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident iure totam corrupti eveniet officia maxime eaque laudantium alias quisquam praesentium voluptatum aliquid, reprehenderit veniam ducimus magni a necessitatibus cumque ipsum pariatur odit blanditiis porro velit perspiciatis asperiores? Sunt explicabo tempora harum fugit sequi eveniet minima itaque dolores aut vitae molestiae tempore maiores, fugiat aspernatur. Tenetur hic itaque obcaecati! Vitae saepe animi quidem similique tempore? Ipsam, voluptatibus. Libero perferendis illum atque ipsam neque tenetur quasi iste perspiciatis repellendus quae eum porro numquam, vitae odio, velit animi cupiditate consequuntur unde dolore laborum suscipit ad sunt. Amet dolore maxime asperiores deleniti dolores! Aspernatur?",
  },
  {
    id: "6",
    caption: "Country Home in the Woods with Attic",
    BR: 3,
    BTH: 3,
    form: "House",
    pet: "Yes",
    maxGuestsAllowed: 9,
    price: 300,
    securityDeposit: 450,
    maxNoOfNights: 7,
    ownersDetails: {
      name: "Roman Altier",
      phoneNo: +234876415678,
      verified: "Yes",
    },
    long: 72.001234,
    lat: 135.2345,
    images: ["./city.jpg", "./mountain.jpg", "./road.jpg"],

    address: {
      street: "54 Forest Blvd.",
      city: "Odasset",
      zipcode: 80123,
    },
    wheelchairAccessibility: "No",
    entrance: "Key",
    Description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident iure totam corrupti eveniet officia maxime eaque laudantium alias quisquam praesentium voluptatum aliquid, reprehenderit veniam ducimus magni a necessitatibus cumque ipsum pariatur odit blanditiis porro velit perspiciatis asperiores? Sunt explicabo tempora harum fugit sequi eveniet minima itaque dolores aut vitae molestiae tempore maiores, fugiat aspernatur. Tenetur hic itaque obcaecati! Vitae saepe animi quidem similique tempore? Ipsam, voluptatibus. Libero perferendis illum atque ipsam neque tenetur quasi iste perspiciatis repellendus quae eum porro numquam, vitae odio, velit animi cupiditate consequuntur unde dolore laborum suscipit ad sunt. Amet dolore maxime asperiores deleniti dolores! Aspernatur?",
  },
];
